Water Based Liquid Scintilator code.

* Basic installation

The script =inst.sh= will install Geant4, ROOT and other basic
packages and can be used to setup the environment.  Run =inst.sh help=
for info.

* Cowbells

This is the COsmic WB(el)LS simulation.  

** Ring the bell

It builds with cmake.

#+begin_src shell
mkdir cowbells-build
cmake -DGeant4_DIR=/path/to/geant4/lib/geant4-9.5.1 \
      -DROOT_DIR=/path/to/root \
      /path/to/cowbells
make
python python/cowbells/prep/gen.py properties.root
#+end_src

** Input data

Input data describing what the simulation should model is specified
via one or more ROOT files.  These files must follow the conventions
described below.  Each type of input data must be located in a
sub-(t)directory of the file.  These sub-directories may be spread
across multiple files or be combined into one.  There is Python code
to assist in generating the input data at
=cowbells/python/cowbells/prep/=.

*** Geometry

The geometry consists of a collection of TGeo classes saved under
=geometry/=.

Details t.b.d.

*** Material Properties

Any optical properties are specified separately from the above They
are specified by adding a TGraph for each property under a
=properties/= sub-(t)directory in the ROOT file following these rules:

 - Must have one directory per material, named the same as the
   material given in the geometry.

 - Must have one TGraph for each property.  It must be named with the
   canonical G4 property name (including capitalization).

 - All TGraphs with exactly one entry are considered scalar properties
   and their X value is ignored.

 - All property values must be converted into native G4 units.  

* WCSim_WbLS based simulation

** Build WCSim with CMake

Install and setup the basics as above.

#+begin_src shell
export WBLSBASE=/path/to/somewhere # just for reference in this example
cd $WBLSBASE
git clone git@github.com:brettviren/WbLS.git
mkdir wcsim-wbls-build
cd wcsim-wbls-build
cmake -DGeant4_dir=$INSTBASE/geant4/lib64/Geant4-9.5.1 \
      -DROOT_DIR=/data3/lbne/bv/wbls/opt/root \
       $WBLSBASE/WbLS/WCSim_WbLS/
make
#+end_src

