Cowbells simulation a simple Geant4 based detector simulation.

Cowbells provides a simple Geant4 based application.  It requires a
detector geometry defined through ROOT TGeo objects and material
properties defined as TGraphs.  Initial kinematics are generated with
built-in methods or by reading in a text file (FIXME: not yet
implemented).  Output is in the form of a ROOT TTree.

* Building

** Prereq

Cmake, Geant4, ROOT and a recent Python are needed.  

The =grinst= project can be used to pre-build the necessary code:

  https://github.com/brettviren/grinst

** Build Cowbells

#+begin_example
cmake -DGeant4_DIR=/path/to/geant4/lib64/Geant4-9.5.1 \
      -DROOT_DIR=/path/to/root/5.32.02 \
      ../cowbells
make 
#+end_example


* Configuration 

** Material Properties

Material properties are specified as TGraphs.  The name of the TGraph
identifies the property name and the TGraph object should be located
in the input TFile in a TDirectory named like =properties/MATERIAL/=.
Scalar properties are TGraphs with a single entry.

*** Scintillation Properties

The standard Geant4 =G4Scintillation= process is used.  The properties
it supports are:

 - =FASTCOMPONENT= :: the fast time component of the scintilation

 - =SLOWCOMPONENT= :: the slow time component of the scintilation

 - =xxxSCINTILLATIONYIELD= :: the per-particle scintillation yield
      (photons/MeV) for particle =xxx= if
      =SetScintillationByParticleType()= has been called.  The
      supported particles are =PROTON=, =DEUTERON=, =TRITON=, =ALHPA=,
      =ION=, =ELECTRON=.

 - =SCINTILLATIONYIELD= :: the scintillation yield (photons/MeV) for
      with no regards to particle type.

 - =RESOLUTIONSCALE= :: 

 - =FASTTIMECONSTANT= ::

 - =FASTSCINTILLATIONRISETIME= ::

 - =SLOWTIMECONSTANT= ::

 - =SLOWSCINTILLATIONRISETIME= ::

 - =YIELDRATIO= :: 

*** Wavelength Shifting Properties

The standard Geant4 =G4OpWLS= process is used.  The properties it
supports are:

 - =WLSCOMPONENT= ::

 - =WLSMEANNUMBERPHOTONS= ::
 
 - =WLSTIMECONSTANT= :: 

 - =WLSABSLENGTH= ::


** Sensitive Detectors

The geometry is defined as ROOT TGeo classes but the sensitive
detector must be told to cowbells.  (FIXME: this is still hard coded).
